function isObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/**
 * Task shape:
 * { id: string, type: string, input: any, expectedOutput?: any }
 */
function validateTask(task) {
  if (!isObject(task)) {
    return 'Task must be an object.';
  }
  if (!task.id || typeof task.id !== 'string') {
    return 'Task id must be a non-empty string.';
  }
  if (!task.type || typeof task.type !== 'string') {
    return 'Task type must be a non-empty string.';
  }
  if (!Object.prototype.hasOwnProperty.call(task, 'input')) {
    return 'Task input is required.';
  }
  return null;
}

function runCodex(task) {
  const validationError = validateTask(task);
  if (validationError) {
    return {
      status: 'failure',
      error: validationError,
    };
  }

  let output;

  if (task.type === 'open_ended_idea' || task.type === 'open_ended_plan' || task.type === 'youtube_analysis') {
    const { spawnSync } = require('child_process');
    const { loadProviderStore } = require('../providerManager');
    const store = loadProviderStore();
    const provider = store.providers && task.providerName ? store.providers[task.providerName] : null;
    const providerType = provider ? provider.type : null;
    const adapterPath =
      providerType === 'xai'
        ? require.resolve('./grokAdapter.js')
        : require.resolve('./openaiAdapter.js');
    let taskInput = task.input || {};
    if (task.type === 'youtube_analysis') {
      const transcriptResult = spawnSync(process.execPath, [require.resolve('../transcriptFetcherCli.js')], {
        env: {
          ...process.env,
          YOUTUBE_TRANSCRIPT_URL: taskInput.url || '',
          YOUTUBE_TRANSCRIPT_LANG: 'en',
        },
        encoding: 'utf8',
        timeout: 8000,
      });
      if (transcriptResult.error || transcriptResult.status !== 0) {
        return { status: 'failure', error: 'Transcript fetch failed to run.' };
      }
      try {
        const parsedTranscript = JSON.parse((transcriptResult.stdout || '').trim() || '{}');
        if (!parsedTranscript.ok) {
          return { status: 'failure', error: parsedTranscript.reason || 'Transcript unavailable.' };
        }
        taskInput = {
          ...taskInput,
          transcript: parsedTranscript.transcript,
          language: parsedTranscript.language,
        };
      } catch {
        return { status: 'failure', error: 'Transcript fetch returned invalid output.' };
      }
    }

    const payload = {
      task: {
        type: task.type,
        input: taskInput,
      },
      providerName: task.providerName || '',
      preferredModel: task.preferredModel || '',
    };
    const result = spawnSync(process.execPath, [adapterPath], {
      env: {
        ...process.env,
        OPENAI_ADAPTER_PAYLOAD: JSON.stringify(payload),
        GROK_ADAPTER_PAYLOAD: JSON.stringify(payload),
      },
      encoding: 'utf8',
      timeout: 15000,
    });
    if (result.error || result.status !== 0) {
      return {
        status: 'failure',
        error: 'LLM adapter failed to run.',
      };
    }
    try {
      const parsed = JSON.parse((result.stdout || '').trim() || '{}');
      if (parsed.status !== 'success') {
        return { status: 'failure', error: parsed.error || 'LLM adapter error.' };
      }
      return { status: 'success', output: parsed.output };
    } catch {
      return { status: 'failure', error: 'OpenAI adapter returned invalid output.' };
    }
  }

  if (task.type === 'web_build_basic') {
    const input = task.input || {};
    if (!input.siteName || typeof input.siteName !== 'string') {
      return { status: 'failure', error: 'siteName is required for web_build_basic.' };
    }
    const html = `<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="utf-8" />\n  <title>${input.siteName}</title>\n  <style>body{font-family:sans-serif;margin:2rem;background:#0b1020;color:#e9ecf5;} .hero{padding:2rem;border-radius:16px;background:linear-gradient(135deg,#1b2138,#232c4d);} .pill{display:inline-block;padding:4px 10px;border-radius:999px;background:#2e385b;color:#9cb4ff;font-size:12px;margin-right:8px;} h1{margin:0 0 12px;} p{margin:0 0 8px;} </style>\n</head>\n<body>\n  <div class="hero">\n    <div class="pill">${input.theme || 'modern'}</div>\n    <h1>${input.siteName}</h1>\n    <p>Static site scaffold generated by assistant1.</p>\n  </div>\n</body>\n</html>`;
    return { status: 'success', output: { html } };
  }

  if (task.type === 'web_clone_basic') {
    const input = task.input || {};
    if (!input.url || typeof input.url !== 'string') {
      return { status: 'failure', error: 'url is required for web_clone_basic.' };
    }
    try {
      const parsed = new URL(input.url);
      const title = parsed.hostname || input.url;
      const htmlOutput = `<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\" />\n  <title>${title}</title>\n  <style>body{font-family:sans-serif;margin:2rem;background:#0b1020;color:#e9ecf5;} .hero{padding:2rem;border-radius:16px;background:linear-gradient(135deg,#1b2138,#232c4d);} .pill{display:inline-block;padding:4px 10px;border-radius:999px;background:#2e385b;color:#9cb4ff;font-size:12px;margin-right:8px;} h1{margin:0 0 12px;} p{margin:0 0 8px;} </style>\n</head>\n<body>\n  <div class=\"hero\">\n    <div class=\"pill\">${input.theme || 'modern'}</div>\n    <h1>${title}</h1>\n    <p>Cloned scaffold inspired by ${title}. Add sections to mirror the source.</p>\n    <p class=\"muted\">Source: ${input.url}</p>\n  </div>\n</body>\n</html>`;
      return { status: 'success', output: { html: htmlOutput } };
    } catch {
      return { status: 'failure', error: 'Invalid source URL.' };
    }
  }

  if (task.type === 'text_transform') {
    const input = task.input;
    if (!isObject(input) || typeof input.text !== 'string' || typeof input.mode !== 'string') {
      return {
        status: 'failure',
        error: 'text_transform requires input { text: string, mode: string }.',
      };
    }
    if (input.mode === 'upper') {
      output = input.text.toUpperCase();
    } else if (input.mode === 'lower') {
      output = input.text.toLowerCase();
    } else {
      return {
        status: 'failure',
        error: 'text_transform mode must be "upper" or "lower".',
      };
    }
  } else if (task.type === 'compute_sum') {
    const input = task.input;
    if (!isObject(input) || !Array.isArray(input.values)) {
      return {
        status: 'failure',
        error: 'compute_sum requires input { values: number[] }.',
      };
    }
    if (!input.values.every((value) => typeof value === 'number')) {
      return {
        status: 'failure',
        error: 'compute_sum values must be numbers.',
      };
    }
    output = input.values.reduce((total, value) => total + value, 0);
  } else {
    return {
      status: 'failure',
      error: `Unsupported task type: ${task.type}`,
    };
  }

  if (Object.prototype.hasOwnProperty.call(task, 'expectedOutput')) {
    const expected = task.expectedOutput;
    if (output !== expected) {
      return {
        status: 'failure',
        error: `Output mismatch. Expected ${JSON.stringify(expected)} but got ${JSON.stringify(output)}.`,
        output,
      };
    }
  }

  return {
    status: 'success',
    output,
  };
}

module.exports = {
  runCodex,
};
